export { fromFabric } from './legacy-fabric.js'
export { paletteKeyFor, SKIN_PALETTES } from './palette.js'
export { DEFAULT_PAGE, DEFAULTS, DocumentError, INK_KINDS, MEDIA_KINDS, OBJECT_TYPES, PAGE, SCHEMA_VERSION, SHAPE_KINDS, TEXT_MODES, emptyDocument } from './schema.js'
export { validateDocument } from './validate.js'
export { JSON_CANVAS_PRESETS, estimateTextBox, isDataUrl, isJsonCanvas, nativeBox, readJsonCanvas, writeJsonCanvas } from './jsoncanvas.js'
export { FOREIGN_TEXT_STYLE, fromJsonCanvas, plainText, plainTextBlocks, svgOf, toJsonCanvas, validateJsonCanvas } from './jsoncanvas-extras.js'
export { createHistory, deepEqual, diffDocuments } from './history.js'
