import { createServer } from 'vite'
import { chromium } from 'playwright'
import { generateStressNote } from '../src/modules/speedtest/stress-note.js'
const note = generateStressNote(5400)
const now = new Date().toISOString()
const summary = { id: 1, resourceId: 'res_bench', revision: 1, noteType: 'canvas', title: 'Benchmark note', notebookId: 1, createdAt: now, updatedAt: now }
const server = await createServer({ server: { port: 4803, strictPort: true, host: '127.0.0.1', proxy: { '/api': 'http://127.0.0.1:4809' } }, logLevel: 'error' })
await server.listen()
const browser = await chromium.launch({ headless: true, args: ['--disable-dev-shm-usage'] })
const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 })
const page = await context.newPage()
page.on('console', (m) => { if (!m.text().startsWith('[vite]')) console.log('PAGE:', m.text()) })
page.on('pageerror', (e) => console.log('PAGEERROR:', e.message))
await page.addInitScript((flags) => { window.__pnPerf = flags }, { pageBitmaps: process.env.MODE ?? 'always' })
await page.route('**/api/**', async (route) => {
  const p = new URL(route.request().url()).pathname.replace(/^\/api/, '')
  const json = (body) => route.fulfill({ contentType: 'application/json', body: JSON.stringify(body) })
  if (p === '/notebooks') return json([{ id: 1, resourceId: 'res_nb', revision: 1, name: 'Bench', color: '#76669a', noteCount: 1 }])
  if (p === '/notes') return json([summary])
  if (p === '/notes/1' && route.request().method() === 'GET') return json({ ...summary, content: note.content, pageState: note.pageState })
  return json({ revision: 2, resourceId: 'res_bench' })
})
await page.goto('http://127.0.0.1:4803/notes')
await page.waitForFunction(() => document.documentElement.dataset.leaferSettled, null, { timeout: 120000 })
await page.waitForTimeout(4000)
const state = () => page.evaluate(() => ({ lod: window.__personalNote.leaferCanvas().lodState(), view: window.__personalNote.leaferCanvas().view() }))
await page.evaluate(() => { const { state, setCanvasViewportOffset } = window.__personalNote; state.canvasZoom = 0.3 / state.displayScale; setCanvasViewportOffset(24, 24) })
await page.waitForTimeout(2500)
console.log('after open', JSON.stringify(await state()))
await page.screenshot({ path: '/var/tmp/f034-vec.png' })
await page.mouse.move(700, 450)
for (let i = 0; i < 20; i += 1) { await page.mouse.wheel(6, 24); await page.evaluate(() => new Promise((r) => requestAnimationFrame(() => r()))) }
console.log('mid pan', JSON.stringify(await state()))
await page.screenshot({ path: '/var/tmp/f034-bitmap.png' })
await page.waitForTimeout(600)
console.log('after pan', JSON.stringify(await state()))
await browser.close()
await server.close()
